### ISSUE TITLE
Wave filling flickering

### ISSUE THREAD

**Issue by aleksai** [soggybag/Sine-Wave#1]
Hi.

Great work! You saved my time.

But I'm experiencing some troubles with unnecessary shape filling flickering, you can see it here:
https://gfycat.com/PaleIllAustraliansilkyterrier

What exactly I mean:

<img width="503" alt="2018-01-19 14 59 30" src="https://user-images.githubusercontent.com/2419256/35140396-a2404a40-fd29-11e7-93a6-b643fcd538a8.png">

Inside drawSineWaves():

    sine.shapeLayer.lineWidth = 1
    sine.shapeLayer.fillColor = UIColor.clear.cgColor
    sine.shapeLayer.strokeColor = sine.color.cgColor

    ...

    shapeLayer.path = sumPath.cgPath
    shapeLayer.lineWidth = 1
    shapeLayer.fillColor = UIColor.clear.cgColor
    shapeLayer.strokeColor = UIColor.white.cgColor

What can it be? I'm already checked that width of view can be divided by length of wave, but no luck.

**Comment by aleksai** [comment]
Fixed by putting `sineView.shapeLayer.fillColor = nil` after this view created.

**Comment by soggybag** [comment]
Thanks for pointing that out. I'll take a look this weekend when I have some time to update the project.
